### ISSUE TITLE
using proxy > traefik

### ISSUE THREAD

**Issue by stkac** [subspacecloud/subspace#11]
Hi everyone!
Does someone know how to use proxy with this?
I mean, some environment available to switch off the key generator? 
Thanks in advance,

**Comment by subspacecloud** [comment]
You can't currently disable Let's Encrypt but this is coming very soon. Thank you.

**Comment by subspacecloud** [comment]
You can run it behind a proxy now with `--letsencrypt=false` on the command line. You can also set the address it listens to like `--http-addr=127.0.0.1:1234`

Please post a comment if there are any problems. Thank you!

**Comment by odensc** [comment]
@subspacecloud What's the recommended way to set this using Docker? Is there a new environment variable, or should I just `docker run [...] /usr/bin/subspace --letsencrypt=false`?

**Comment by subspacecloud** [comment]
Thanks for pointing out that I forgot to add ENV options for this!

They're added now. You can use `--env SUBSPACE_LETSENCRYPT=false` and `--env SUBSPACE_HTTP_ADDR=127.0.0.1:1234` or whatever your configuration calls for.

Please post a comment if you have any problems. Thanks again!

**Comment by anibal-aguila** [comment]
@subspacecloud for future reference, the error:
**RTNETLINK answers: Permission denied**

was solved in docker whit:

`--sysctl net.ipv6.conf.all.disable_ipv6=0`

**Comment by duanedtp** [comment]
> Thanks for pointing out that I forgot to add ENV options for this!
> 
> They're added now. You can use `--env SUBSPACE_LETSENCRYPT=false` and `--env SUBSPACE_HTTP_ADDR=127.0.0.1:1234` or whatever your configuration calls for.
> 
> Please post a comment if you have any problems. Thanks again!

i was finally able to access the web page after applying these two lines to docker create. But i've ran into another issue, after signing up, i'm unable to login. Just keeps returning to the login page

**Comment by Spass1966** [comment]
@subspacecloud Synology DS-218+. I've thrown everything at this and can't get a live page.

```
  subspace:
    image: subspacecloud/subspace:latest
    container_name: subspace
    command: --sysctl net.ipv6.conf.all.disable_ipv6=0
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - ./subspace/data:/data
      - /volume1/@appstore/WireGuard/wireguard/wg:/usr/bin/wg
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:subspace.${DOMAIN}"
      - "traefik.port=1234"
    environment:
      - SUBSPACE_HTTP_HOST=subspace.hansen.agency
      - SUBSPACE_LETSENCRYPT=false
      - SUBSPACE_HTTP_ADDR=127.0.0.1:1234
    restart: "always"
```

`docker logs subspace`
```                
+ '[' -z subspace.{$DOMAIN} ']'
+ '[' -z '' ']'
+ export SUBSPACE_BACKLINK=
+ SUBSPACE_BACKLINK=
+ '[' -z false ']'
+ '[' -z 127.0.0.1:1234 ']'
+ '[' -z '' ']'
+ export SUBSPACE_HTTP_INSECURE=false
+ SUBSPACE_HTTP_INSECURE=false
+ export NAMESERVER=1.1.1.1
+ NAMESERVER=1.1.1.1
+ export DEBIAN_FRONTEND=noninteractive
+ DEBIAN_FRONTEND=noninteractive
+ echo 'nameserver 1.1.1.1'
+ /sbin/iptables -t nat --check POSTROUTING -s 10.99.97.0/24 -j MASQUERADE
+ /sbin/iptables --check FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
+ /sbin/iptables --check FORWARD -s 10.99.97.0/24 -j ACCEPT
```
